In [7]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns 


df = pd.read_csv('D:/dataFest 2026/DataFest-2026-ENERGICAL-DATA-INTELLIGENCE/energical_transactions_anonymized.csv', index_col='id_transaction')
df.head(10)

,id_commande_anon,id_client,type_client,nouveau_ou_fidele,date_commande,wilaya,categorie_produit,produit,quantite,montant_da,moyen_paiement,statut_commande
id_transaction,,,,,,,,,,,,
1,10872,CLT_02355,B2C,Returning,2022-01-03,Laghouat,Électricité,Electrode détecteur,3.0,826.05,Paiement à la livraison,Terminée
2,12712,CLT_00422,B2C,New,2022-12-08,Adrar,Électricité,Interrupteur Simple Allumage DIAA Métal,4.0,2024.10,Paiement à la livraison,Terminée
3,17642,CLT_03812,B2C,Returning,2024-06-10,Mila,Sanitaire,Capteur de débit pour chauffe-eau à T° const,3.0,1271.90,Paiement à la livraison,En livraison par NOEST
4,16497,CLT_02886,B2C,Returning,2024-01-31,Boumerdès,Électricité,Prise simple DIAA Acrylique - Bois,2.0,702.05,Paiement à la livraison,Terminée
5,17671,CLT_00452,B2C,New,2024-06-13,Alger,Sanitaire,Chauffe-eau à température constante XCT-12L (G...,1.0,27352.74,Paiement à la livraison,Terminée
6,10399,CLT_04052,B2B,Returning,2021-09-27,Djelfa,Électricité,Doorbell - Grey,1.0,8011.62,Paiement à la livraison,Terminée
7,14134,CLT_03080,B2C,Returning,2023-05-21,Tipaza,Électricité,Disjoncteur différentiel sensible 300mA mono N...,15.0,34209.25,Paiement par chèque,Terminée
8,17332,CLT_03770,B2C,Returning,2024-05-03,Sétif,Pièces de rechange pour S.A.V.,Pressostat,1.0,861.61,CIB / EDAHABIA,Terminée
9,10245,CLT_04093,B2C,New,2021-08-21,Skikda,Électricité,Gray electric lock,1.0,5888.13,Paiement à la livraison,Terminée
10,17301,CLT_03812,B2C,Returning,2024-04-28,Mila,Sanitaire,Capteur de pression d’eau,10.0,3647.03,Paiement à la livraison,Terminée

In [8]:
df.columns

Index(['id_commande_anon', 'id_client', 'type_client', 'nouveau_ou_fidele',
       'date_commande', 'wilaya', 'categorie_produit', 'produit', 'quantite',
       'montant_da', 'moyen_paiement', 'statut_commande'],
      dtype='object')

In [9]:
df.dtypes

id_commande_anon       int64
id_client             object
type_client           object
nouveau_ou_fidele     object
date_commande         object
wilaya                object
categorie_produit     object
produit               object
quantite             float64
montant_da           float64
moyen_paiement        object
statut_commande       object
dtype: object

In [10]:
df.shape

(17263, 12)

In [11]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 17263 entries, 1 to 17263
Data columns (total 12 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   id_commande_anon   17263 non-null  int64
 1   id_client          17263 non-null  object
 2   type_client        17263 non-null  object
 3   nouveau_ou_fidele  17263 non-null  object
 4   date_commande      17247 non-null  object
 5   wilaya             17263 non-null  object
 6   categorie_produit  17263 non-null  object
 7   produit            17153 non-null  object
 8   quantite           17162 non-null  float64
 9   montant_da         17162 non-null  float64
 10  moyen_paiement     17252 non-null  object
 11  statut_commande    17263 non-null  object
dtypes: float64(2), int64(1), object(9)
memory usage: 1.7+ MB

In [12]:
df.describe()

       id_commande_anon      quantite    montant_da
count      17263.000000  17162.000000  1.716200e+04
mean       13991.589179      4.761391  1.312400e+04
std         2265.715692     27.405937  8.110114e+04
min        10000.000000      1.000000 -1.273270e+04
25%        11991.500000      1.000000  9.847000e+02
50%        14047.000000      1.000000  3.092465e+03
75%        15997.500000      3.000000  8.807580e+03
max        17744.000000   1920.000000  9.062875e+06